services:
  redis:
    image: "redis:7.0.10-bullseye"
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"

  web:
    build: ./web
    ports:
      - "80:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - backend-network
    depends_on:
      - redis

networks:
  backend-network:

volumes:
  redis-volume: